GET http://localhost:8080/todos/1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImpvaG5kb2VAZ21haWwuY29tIiwiZXhwIjoxNzI0NjczNzExLCJ1c2VySWQiOjEwfQ.A54yj6VzdG2-yzGonGz061JpSgZ3xcFQ8uDe-eRjyZs
